apiVersion: constraints.gatekeeper.sh/v1beta1
kind: BlockTokenRequest
metadata:
  name: block-token-terraform-ns
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["ServiceAccount"]
    namespaces:
      - terraform
  parameters:
    exemptServiceAccounts: []
