apiVersion: v1
kind: ConfigMap
metadata:
  name: iac-platform
  namespace: terraform
  labels:
    app.kubernetes.io/name: iac-platform
data:
  SERVER_PORT: "8080"
  CC_SERVER_PORT: "8090"
  SERVER_HOST: "0.0.0.0"
  ENV: "production"
  DB_HOST: "iac-postgres"
  DB_PORT: "5432"
  DB_NAME: "iac_platform"
  DB_SSLMODE: "disable"
  #DB_SSLMODE: "require"
  TZ: "Asia/Singapore"
