apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - ha-rbac.yaml
  - service-backend.yaml
  - service-frontend.yaml
  - deployment-backend.yaml
  - deployment-frontend.yaml
