apiVersion: v1
kind: Secret
metadata:
  name: iac-platform
  namespace: terraform
  labels:
    app.kubernetes.io/name: iac-platform
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres123"
  JWT_SECRET: "your-jwt-secret-key"
